config/routes.rb
Rails.application.routes.draw do

  get 'my_orders' => 'orders#my_orders'

  post 'add_to_cart' => 'cart#add_to_cart'

  post 'order_complete' => 'cart#order_complete'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  delete 'delete_line_item' => 'cart#delete_line_item'

  delete 'cancel_checkout' => 'cart#cancel_checkout'

  devise_for :users
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

before_action :authenticate_user!, only: [:checkout]

  def add_to_cart
  	# line_item = LineItem.new
  	# line_item.product_id = params[:product_id]
  	# line_item.quantity = params[:quantity]
  	# line_item.line_item_total = line_item.product.price * line_item.quantity
  	# line_item.save
    @order = current_order
  	if params[:quantity].blank?
  		flash[:error] = "Select Quantity."
  		redirect_to root_path
  	else
  	line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
    @order.save
    session[:order_id] = @order.id
  	line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

  	redirect_to view_order_path
  	end

  end

  def view_order
  	@line_items = current_order.line_items
  end

  def delete_line_item
  	line_item = LineItem.find(params[:line_item_id])
  	line_item.destroy

  	redirect_to view_order_path
  end

  def checkout

  	line_items = current_order.line_items
    @order = current_order
  	@order.update(user_id: current_user.id, subtotal: 0)

  	line_items.each do |line_item|

  		line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))

  		if @order.order_items[line_item.product_id].nil?
  			@order.order_items[line_item.product_id] = line_item.quantity
  		else 
  			@order.order_items[line_item.product_id] += line_item.quantity 
  		end

  		@order.subtotal += line_item.line_item_total
  	end
  	@order.save
  	@order.update(sales_tax: (@order.subtotal * 0.08))
  	@order.update(grand_total:(@order.sales_tax + @order.subtotal))

  end

  def order_complete

    line_items = current_order.line_items

    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'SecondBest Buy Customer',
      :currency    => 'usd'
      )

    session.delete(:order_id)
    line_items.destroy_all

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  def cancel_checkout
    session.delete(:order_id)
    Order.find(params[:order_id]).destroy

    redirect_to root_path
    
  end



end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/checkout.html.erb
<div class="jumbotron">
<h2>Thanks for Shopping with SecondBest Buy!</h2>
</div>
<p>Order Summary:</p>

<table class="table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Unit Price</th>
			<th>Total Price</th>
		</tr>
	</thead>
	<tbody>
		<% @order.order_items.each do |key,value| %>
			<tr>
				<td><%= Product.find(key).name %></td>
				<td><%= value %></td>
				<td><%= number_to_currency Product.find(key).price %></td>
				<td><%= number_to_currency Product.find(key).price * value %></td>
			</tr>
			<% end %>
	</tbody>
</table>

<p>
	<strong>Subtotal:</strong> <%= number_to_currency @order.subtotal %>
</p>
<p>
	<strong>Tax:</strong> <%= number_to_currency @order.sales_tax %>
</p>
<p>
	<strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

<div class="ilb">
	<%= form_tag order_complete_path do %>
	<%= hidden_field_tag :order_id, @order.id %>
	<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Order #<%= @order.id %>" data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>

</div>

	<%= link_to "Cancel Order", cancel_checkout_path(order_id: @order.id), method: :delete, class: "btn btn-danger", data:{ confirm: "Are You Sure?"} %>

app/views/cart/order_complete.html.erb
<div class="jumbotron">
<h2>Thank you for your order!</h2>
<p><strong>Your order will be shipping to you in 4 to 90 weeks(What did you expect we are called SecondBest Buy for a reason). Email confirmation sent to  <%= @order.user.email %>!</strong></p>
</div>

app/views/cart/view_order.html.erb
<div class="jumbotron">
<h2>Your Cart</h2>
</div>

<table class="table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Unit Price</th>
			<th>Quantity</th>
			<th>Total Price</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @line_items.each do |line_item| %>
			<tr>
				<td><%= line_item.product.name %></td>
				<td><%= number_to_currency line_item.product.price %></td>
				<td><%= line_item.quantity %></td>
				<td><%= number_to_currency line_item.line_item_total %></td>
				<td><%= link_to "Remove from Cart", delete_line_item_path(line_item_id: line_item.id), method: :delete, class: "btn btn-danger", data:{ confirm: "Are You Sure?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<% unless @line_items.empty? %>
<%= link_to "Checkout", checkout_path, class: "btn btn-success" %>
<% end %>
<%= link_to "Continue Shopping", root_path, class: "btn btn-info" %> 